### task-1

In [59]:
import numpy as np

In [60]:
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]], dtype=float)
print(type(a))

<class 'numpy.ndarray'>


In [61]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

### task-2

In [62]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### task-3

In [83]:
# b = a_centered[:,0] @ a_centered[:,1]
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])
a_centered_sp = a_centered_sp / (a_centered.shape[0] - 1)
a_centered_sp

2.0

### task-4

In [95]:
a = a.transpose()
cv = np.cov(a)
cv
# Все получилось но почему cv[0][1] дает совсм нето значение
# которое можно наблюдать при вызове cv ?

array([[1. , 2. ],
       [2. , 4.3]])