In [2]:
import numpy as np
import pandas as pd

In [3]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### task 2

Создать 5 двумерных массивов разной формы из массива a.
Не использовать в аргументах метода reshape число -1.

In [4]:
print(a.reshape(4, 3), end='\n\n')
print(a.reshape(3, 4), end='\n\n')
print(np.reshape(a, (6, 2)), end='\n\n')
print(np.reshape(a, (2, 6)), end='\n\n')
print(np.reshape(a, (12, 1)), end='\n\n')
print(np.reshape(a, (3, 2, 2)), 'three dimensions', sep='\t')

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]

[[[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]	three dimensions


### task 3

Создать 5 двумерных массивов разной формы из массива a. Использовать
в аргументах метода reshape число -1 (в трех примерах - для обозначения
числа столбцов, в двух - для строк).

In [5]:
print(a.reshape(-1, 2), end='\n\n')
print(a.reshape(-1, 4), end='\n\n')
print(np.reshape(a, (12, -1)), end='\n\n')
print(np.reshape(a, (2, -1)), end='\n\n')
print(a.reshape(6, -1))

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


## task 4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк,
назвать одномерным?

Answer: Not

### task 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных
чисел с плавающей запятой из нормального распределения со средним,
равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из
этого массива одномерный массив с таким же атрибутом size, как и
исходный массив.

In [6]:
an = np.random.randn(3, 4)
an

array([[-2.11245815,  0.18213256, -0.82078082, -1.93358715],
       [ 2.12068897,  0.68381399,  0.1449369 , -0.15384873],
       [-0.34254067, -0.45278841, -1.16776255,  0.72672241]])

In [7]:
a_dimension_1 =  an.flatten()

an.size == a_dimension_1.size

True

### task 6

Создать массив a, состоящий из целых чисел, убывающих
от 20 до 0 невключительно с интервалом 2.

In [8]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### task 7

Создать массив b, состоящий из 1 строки и 10 столбцов: целых
чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем
разница между массивами a и b?

In [9]:
b = np.array([ i for i in  range(20, 1, -2)])
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [10]:
print(type(a) == type(b))
print(a.size == b.size)

True
True


### There is no difference between array a and b

### task 8

Вертикально соединить массивы a и b. a - двумерный массив из
нулей, число строк которого больше 1 и на 1 меньше, чем число
строк двумерного массива b, состоящего из единиц. Итоговый массив v
должен иметь атрибут size, равный 10.

In [23]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
print(a, end='\n\n')
print(b)
v = np.concatenate((a, b), axis=0)
# v = np.vstack((a, b))
print(v.size==10)
v

[[0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]
True


array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### task 9

Создать одномерный массив а, состоящий из последовательности целых
чисел от 0 до 12. Поменять форму этого массива, чтобы получилась
матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.
Получить матрицу At путем транспонирования матрицы A. Получить матрицу B,
умножив матрицу A на матрицу At с помощью матричного умножения. Какой
размер имеет матрица B? Получится ли вычислить обратную матрицу для
матрицы B и почему?

In [97]:
a = np.arange(0, 12)
A = a.reshape(4, 3)
At = A.T
B = A.dot(At)
print(B)
np.linalg.inv(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


LinAlgError: Singular matrix

Какой размер имеет матрица B?
Answer: we get a 3-by-3 or 4-by-4 matrix.

Получится ли вычислить обратную матрицу для матрицы B и почему?
Answer: it is possible, if B = At.dot (A), this matrix is square,
otherwise there is no B = A.dot (At), because
this singular matrix

### task 10

Инициализируйте генератор случайных числе с помощью объекта
seed, равного 42.

In [77]:
np.random.seed(42)
np.random.sample()

0.3745401188473625

### task 11

Создайте одномерный массив c, составленный из последовательности
16-ти случайных равномерно распределенных целых чисел от 0 до 16
невключительно.

In [87]:
an = np.random.randint(low=0, high=16, size=16)
an

array([11,  1,  0, 15,  6,  6, 13,  7,  4,  2, 11,  7,  5, 10,  2,  0])

### task 12

Поменяйте его форму так, чтобы получилась квадратная матрица C.
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего
вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг
и обратную матрицу D_inv для D.

In [123]:
C = an.reshape(4,4)
B = B * 10
D = np.add(C, B)
print(np.float32(np.linalg.det(D)))
print(np.linalg.matrix_rank(D))
D_inv = np.linalg.inv(D)
D_inv

3.7002e+37
4


array([[-3.44508627e-11, -2.32830644e-10,  1.33039993e-10,
         2.67281507e-10],
       [-2.32830644e-10,  2.32830642e-10,  2.32830642e-10,
        -2.32830644e-10],
       [ 1.33039991e-10,  2.32830644e-10,  3.17157525e-10,
         9.97906515e-11],
       [ 2.67281506e-10, -2.32830641e-10,  9.97906523e-11,
        -2.67281507e-10]])

### Task 13

Приравняйте к нулю отрицательные числа в матрице D_inv,
а положительные - к единице. Убедитесь, что в матрице D_inv остались
только нули и единицы. С помощью функции numpy.where, используя
матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников
данных, получите матрицу E размером 4x4.  Элементы матрицы E, для
которых соответствующий элемент матрицы D_inv равен 1, должны быть
равны соответствующему элементу матрицы B, а элементы матрицы E,
для которых соответствующий элемент матрицы D_inv равен 0, должны
быть равны соответствующему элементу матрицы C.

In [137]:
D_inv[D > 0] = 1
D_inv[D < 0] = 0
print(D_inv)
print(B, 'B')
print(C, 'C')
E = B.copy()
E[np.where(D_inv == 0)] = C[np.where(D_inv == 0)]
E

[[0. 0. 1. 1.]
 [0. 0. 1. 0.]
 [1. 1. 1. 1.]
 [1. 0. 1. 0.]]
[[-1316487168 -1968177152  1675100160  1023410176]
 [-1968177152  -279969792  1408237568 -1198522368]
 [ 1675100160  1408237568  1141374976   874512384]
 [ 1023410176 -1198522368   874512384 -1347420160]] B
[[11  1  0 15]
 [ 6  6 13  7]
 [ 4  2 11  7]
 [ 5 10  2  0]] C


array([[        11,          1, 1675100160, 1023410176],
       [         6,          6, 1408237568,          7],
       [1675100160, 1408237568, 1141374976,  874512384],
       [1023410176,         10,  874512384,          0]])